#! /usr/bin/expect -f

package require Thread 
set t [thread::create]  ;# Create a thread 

spawn ./server97d
expect -exact "$ input command >"
send -- "s\r"
expect -exact "in Handler()"
expect -exact "exit MyTask2::svc()"

thread::send -async $t {exec ./autorun-client}

expect -exact "exit MyTask::svc()"
expect -exact "$ input command >"
send -- "q\r"
expect -exact "in MyTask::~MyTask() 1"