#! /usr/bin/expect -f

spawn ./server99d
expect -exact "$ input command >"
send -- "s\r"
expect -exact "main::start"
expect -exact "in Handler()"
expect -exact "exit MyTask2::svc()"
exec ./client 2>/dev/null
exec ./client 2>/dev/null
expect -exact "exit MyTask::svc()"
expect -exact "main::end"
expect -exact "$ input command >"
send -- "s\r"
expect -exact "main::start"
expect -exact "in Handler()"
expect -exact "exit MyTask2::svc()"
exec ./client 2>/dev/null
exec ./client 2>/dev/null
expect -exact "exit MyTask::svc()"
expect -exact "main::end"
expect -exact "$ input command >"
send -- "q\r"
expect -exact "in MyTask::~MyTask() 1"